server:
  http_listen_port: 3200
  grpc_listen_port: 9095

auth_enabled: false

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 5m
  max_block_bytes: 100_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces


overrides:
  per_tenant_override_config: /etc/tempo/overrides.yaml